services:
  - type: web
    name: kreta-bandhu-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node databaseServer.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 3005
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1
